### ISSUE TITLE
Missing numeric_limits methods for int types

### ISSUE THREAD

**Issue by abialas1** [KhronosGroup/libclcxx#10]
The following methods are not defined for int types (char, uchar, short, ushort, int, uint, long, ulong), which cause kernel compilation failures:

numeric_limits<T>::epsilon()
numeric_limits<T>::round_error()
numeric_limits<T>::infinity()
numeric_limits<T>::quiet_NaN()
numeric_limits<T>::signaling_NaN()
numeric_limits<T>::denorm_min()

Despite these refer to float-related numbers, the spec does allow to use them with all types. These values are also defined in http://en.cppreference.com/w/cpp/types/numeric_limits for all types (they should be all zeroes for int types).

**Comment by AnastasiaStulova** [comment]
Closing this issue since the project has changed its direction. Feel free to reopen if it is still found relevant.
