### ISSUE TITLE
OpenCL 2.2 CTS needs lit_tests_cl22 branch..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/libclcxx#15]
reading OpenCL-CTS/readme-spir-v-binaries.txt says:
libclcxx
Repository: https://gitlab.khronos.org/opencl/libclcxx 
Branch: lit_tests_cl22   

gitlab can't be accessed for a non Khronos user so can upload  lit_tests_cl22 branch?

**Comment by AnastasiaStulova** [comment]
Closing this issue since the project has changed its direction. Feel free to reopen if it is still found relevant.
