### ISSUE TITLE
vulkan

### ISSUE THREAD

**Issue by fhoenig** [KhronosGroup/libclcxx#17]
Just getting a bit into Spir-V (coming from cuda), so please apologize if this questions sounds naive:
Can this spir-v output be run as Vulkan compute shader in any form?

**Comment by bader** [comment]
Unfortunately "spir-v output" from OpenCL C++ compiler is always uses "Kernel" execution model, so it can't be run as Vulkan compute shader.
You might take a look at clspv - a prototype compiler for a subset of OpenCL C to Vulkan compute shaders. 
https://github.com/google/clspv

**Comment by AnastasiaStulova** [comment]
I think this question is now answered as there seem to be no outstanding issues.
