### ISSUE TITLE
Incorrect values of event_profiling_info and event_status enums

### ISSUE THREAD

**Issue by ex-rzr** [KhronosGroup/libclcxx#6]
Values of these enums are not explicitly set (so they are 0, 1...).

https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#_a_id_kernel_profiling_info_a_kernel_profiling_info
> **0x1 CmdExecTime**  Indicates that the profiling info queried is the execution time.
```cpp
enum class event_profiling_info : int
{
    exec_time // == 0, should be 1
};
```

https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpCreateUserEvent
> OpCreateUserEvent
Create a user event. The execution status of the created event is set to a value of **2** (CL_SUBMITTED).

https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpSetUserEventStatus
> OpSetUserEventStatus
Sets the execution status of a user event specified by Event.Status can be either **0** (CL_COMPLETE) to indicate that this kernel and all its child kernels finished execution successfully, or **a negative integer** value indicating an error.

```cpp
enum class event_status : int
{
    submitted, // == 0, should be 2
    complete, // == 1, should be 0
    error // == 2, should be negative (-1?)
};
```

**Comment by bsochack** [comment]
Right, this one should be fixed

**Comment by AnastasiaStulova** [comment]
Closing this issue since the project has changed its direction. Feel free to reopen if it is still found relevant.
