### ISSUE TITLE
Usage of OpEnqueueKernel (possibly) violates SPIR-V specification

### ISSUE THREAD

**Issue by ex-rzr** [KhronosGroup/libclcxx#7]
https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpEnqueueKernel

https://github.com/KhronosGroup/libclcxx/blob/master/include/__ocl_enqueue_helpers.h#L222

OpEnqueueKernel is used with zero values of *Param Size* and *Param Align*.
I don't know is this incorrect or not , but I can imagine scenarios where these values are  needed, for example, if some implementation will need to copy *Param* before calling *Invoke* on the copy (SPIR-V specification does not restrict this).

**Comment by b-sumner** [comment]
Param Size and Param Align need to be non-zero and correct for at least one implementation.  It's certainly information the compiler has.

**Comment by bsochack** [comment]
@b-sumner , that's actually not true. We don't know the size of opaque types (images, pipes and so on). The size is known by device specific backend compiler. It's the main reason why we don't provide this information.

**Comment by bsochack** [comment]
We can try to use OpSizeOf instruction to get this information, but it's actually the same as backtracking Param and checking the structure definition. What we can promise is to always provide strongly typed pointer as Param (not void*).

**Comment by b-sumner** [comment]
Makes sense.  Just as with SPIR-2.0, we need to try to ensure that information about the size and alignment of the captured variables can be determined at some point during compilation.

**Comment by AnastasiaStulova** [comment]
Closing this issue since the project has changed its direction. Feel free to reopen if it is still found relevant.
