### ISSUE TITLE
OpImageQuerySizeLod should be used instead of OpImageQuerySize

### ISSUE THREAD

**Issue by ex-rzr** [KhronosGroup/libclcxx#8]
These image functions: `width()`, `height()`, `depth()`, `array_size()`, `size()` must use `OpImageQuerySizeLod` with LOD = 0 for images with and without mipmaps (except for `image1d_buffer` and multi-sampled images `*_ms` which don't support mipmaps).

https://www.khronos.org/registry/spir-v/specs/1.1/SPIRV.html#OpImageQuerySize
> Image ... It cannot be an image with level of detail; there is no implicit level-of-detail consumed by this instruction.

At this moment `OpImageQuerySize` is used for functions (width, height, depth, array_size and size) without lod even for mipmap images:  
https://github.com/KhronosGroup/libclcxx/blob/master/include/__ocl_image_traits.h#L242

**Comment by AnastasiaStulova** [comment]
Closing this issue since the project has changed its direction. Feel free to reopen if it is still found relevant.
